dkhamsing/open-source-ios-apps

- README.md
- non-app-store-ios-apps.md
> Create list for apps not in the store, resolve #1

- non-app-store-ios-apps.md
Thanks for putting this list together, @dkhamsing!
> Added CardsAgainst

- README.md
Here is my little contribution. Great initiative :+1:
> Added Vinylogue

- non-app-store-ios-apps.md
Hey @orta @ashfurrow @1aurabrown
1. Is Eidolon on the App Store?
2. What's the name  of the app (what's the bundle display name)?
Thanks
> Add Eidolon by @artsy

- README.md
[Eigen](https://cloud.githubusercontent.com/assets/2352972/6168923/85b5810c-b2da-11e4-850f-0916c753bd1b.png) and [Concurrency](https://cloud.githubusercontent.com/assets/2352972/6168935/a594616e-b2da-11e4-9a9e-94107e21e202.png) are actually Objective-C apps.
> Fixing apps language

- README.md
I have added the official WordPress app which is open-source.
> WordPress Added

- non-app-store-ios-apps.md
Add the [HackerNews](https://github.com/amitburst/HackerNews) app.
> Add HackerNews app

- non-app-store-ios-apps.md
Via https://github.com/sanketfirodiya/sample-watchkit-apps, thanks @sanketfirodiya
> Apple Watch apps

- README.md
[Here is Bither's watch app](https://github.com/bither/bither-ios/tree/master/bither-ios%20WatchKit%20Extension)
> Bither also has a watch app

- README.md
> Adding new iOS app

- README.md
...in a new `Developer` section (controversy!)
> Added Bequest

- README.md
> Add Gulps  

- README.md
Hi!
I've been searching for OSS iOS projects to do research on common licenses (thanks so much for this resource!), and a friend pointed me towards ownCloud's app, which isn't on your list.
> Add ownCloud

- README.md
WeatherMap overlays weather information on a map, giving you a clear picture of weather around you, with the ability to browse into the future.
> Add WeatherMap

- README.md
I've just open-sourced [MUDRammer — A Modern MUD Client for iPhone and iPad](https://github.com/splinesoft/MUDRammer), my pride and joy :)
> > invoke incantation of MUDRammer reveal

- README.md
Added WatchStocks app & link to github page.
> Added WatchStocks app

- README.md
> Add Coding

- README.md
Reverts dkhamsing/open-source-ios-apps#121 :cry:
> Revert "Add BlockParty"

- README.md
> Adding GrinnellEvents

- README.md
> Adding QiitaCollection

- README.md
> Adding ProMonster

- README.md
> Adding Sunning Store

- README.md
> Update React Native section

- README.md
added swift diamond icon, plus extra fire icon to represent 1000+ stars on Swift-Radio-Pro
> updated Swift-Radio-Pro icons

- README.md
> Add Todo.txt 

- README.md
https://github.com/hanton/HTY360Player
> Add 360 VR Player

- README.md
https://github.com/hkalexling/KonaBot-iOS
> Add Konabot

- README.md
- archive.md
- Add Adblock Plus by @adblockplus, close #161
- Mume project was deleted 
> https://travis-ci.org/dkhamsing/open-source-ios-apps/builds/96763135
> 404: https://github.com/coderyi/Mume
> Adblock Plus

- README.md
- archive.md
> Move Hackers

- README.md
> Add Tether 

- README.md
- archive.md
> Remove suning

- README.md
> Markdown links

- README.md
> Location Update

- README.md
GoodNight is in active development and a nice app for automatic temperature/gamma adjustment. It is originally based on GammaThingy.
> GoodNight added

- README.md
Update 360 VR Player's Stars Indicator
> Update 360 VR Player

- README.md
https://github.com/nathunsmitty/MirrorPlusPlus
> Add Mirror++

- README.md
https://github.com/wrutkowski/Lucid-Weather-Clock with post on Medium: https://medium.com/@wrutkowski/lucid-weather-clock-954f6ce8bd0e
> Added Lucid Weather Clock App

- README.md
For projects listed twice
Close #177
> App Store Links

- README.md
> Add BLEMeshChat  

- README.md
> Add Depressed 

- README.md
> Update Hacker News  

- README.md
> Move projects to Location

- README.md
Thanks for curating this awesome list! I am submitting my latest project, "Swift Synth" for inclusion. Thank you for your consideration. 🎹
> added Swift Synth, updated name of my other project (Swift Radio Pro)

- README.md
> Add Colloquy 

- README.md
> Communication Update

- README.md
> React Native Update

- README.md
> Added MiniKeePass app

- README.md
for Issue #222
Sorry, I have added EX Player to wrong category
> Moved EX Player to correct category

- README.md
add open sourced game Mission999
> add Game Mission999

- README.md
> Apple Watch Update

- README.md
- Yorkie: This app will help you, in an easy way, taking care of your dog.
- https://github.com/carlbutron/YorkieApp
- https://itunes.apple.com/en/app/Yorkie/id1000836606
> Added Yorkie by @carlbutron

- README.md
> Add Ionic section + Add Vegan Lists UK by @dsgriffin

- README.md
3. [ ] Avoid iOS or open-source in description as it is assumed :-)
5. [x] Follow the following template (use 🔶 for Swift projects)
> Add littlego by @herzbube

- README.md
surespot is a mobile messaging application that secures all messages using end-to-end encryption.
> add surespot  official iOS client

- README.md
1. Create Reactive Programming section
- Move ReactiveCocoa there as sub section
- Create RXSwift sub section
- Move Kiosk to RXSwift sub section
Close #240
> Reactive Programming section

- README.md
Consolidate categories into a "Special" section
> Special section 

- README.md
5. [x] Use format below for your entry (use 🔶 for Swift projects)
> Add RWDevCon by @raywenderlich

- README.md
5. [x] Use approved format for your entry (use 🔶 for Swift projects)
> Add Sakura Fly by @l800891

- README.md
5. [x] Use approved format for your entry (use 🔶 for Swift projects)
> Add GitHub API Client by @tailec

- README.md
> Update star count for GitHub API Client

- README.md
Update README file with Knock-To-React and Borrowed Books - UFRGS.
> Update with Knock-To-React and Borrowed Books - UFRGS

- README.md
5. [x] Use approved format for your entry (use 🔶 for Swift projects)
> Add CI2Go by @ngs

- README.md
> Add LVMC-Demo-Alloy-App by @falkolab

- README.md
1. [ ] One project per pull request
2. [ ] Insert the project in alphabetical order
3. [ ] Avoid iOS or open-source in description as it is assumed 
4. [ ] Use this commit title format if applicable: Add app-name by @github-username
5. [ ] Use approved format for your entry (use 🔶 for Swift projects)
> Add LogU iOS

- README.md
1. [ ] One project per pull request
2. [ ] Insert the project in alphabetical order
3. [ ] Avoid iOS or open-source in description as it is assumed 
4. [ ] Use this commit title format if applicable: Add app-name by @github-username
5. [ ] Use approved format for your entry (use 🔶 for Swift projects)
Line 173
> Add Codinator iOS

- README.md
- App name: Tracker 4 Compassion
- source url, i.e. https://github.com/fokkezb/tracker
- https://itunes.apple.com/nl/app/g.o.-tracker-4-compassion/id1100240821?mt=8
> Add Appcelerator Tracker App by @fokkezb

- README.md
5. [x] Use approved format for your entry (use 🔶 for Swift projects)
> Add OpenShop.io by @Skornos

- README.md
> add second flame to ownCloud iOS app for reaching 200 stars

- README.md
1. [X] Project URL: https://github.com/kiliankoe/ParkenDD
2. [X] One project per pull request
3. [X] Insert the project in alphabetical order
4. [X] Avoid iOS or open-source in description as it is assumed 
6. [X] Use approved format for your entry (use 🔶 for Swift projects)
Thanks for the list 😊
> Add ParkenDD by @kiliankoe

- README.md
1. [x] Project URL: https://github.com/vanyaland/ToThePenny
3. [x] Insert the project in alphabetical order
4. [x] Avoid iOS or open-source in description as it is assumed 
6. [x] Use approved format for your entry (use 🔶 for Swift projects)
> Add ToThePenny by @vanyaland

- README.md
1. [ ] Project URL: 
3. [ ] Insert the project in alphabetical order
4. [ ] Avoid iOS or open-source in description as it is assumed 
6. [ ] Use approved format for your entry (use 🔶 for Swift projects)
> Adding Five in a row

- README.md
1. [x] Project URL: 
3. [x] Insert the project in alphabetical order
4. [x] Avoid iOS or open-source in description as it is assumed 
6. [x] Use approved format for your entry (use 🔶 for Swift projects)
> Adding AppLove for section[Developer]

- README.md
1. [x] Project URL: 
3. [x] Insert the project in alphabetical order
4. [x] Avoid iOS or open-source in description as it is assumed 
6. [x] Use approved format for your entry (use 🔶 for Swift projects)
> Adding Doctor Nearby iOS

- contents.json
1. [x] Project URL: https://github.com/BalestraPatrick/RealmVideo",
3. [x] Insert the project in alphabetical order
> Add RealmVideo 

- contents.json
> Add Rails Cast Apple TV App

- contents.json
In contents.json file i have added wrong category.Please to check and the latest one.Thank You
> Update Category for Rails Casts app

- contents.json
0. [x] Project URL: none. my personal site is www.adriancedwards.com
> Add MetricTime by @DeveloperACE

- contents.json
0. [x] Project URL: https://github.com/peteog/Closebox
> Add Closebox by @peteog

- contents.json
> Add MiamiSunglasses by @DeveloperACE

- contents.json
> Add Sentiments by @kyleweiner

- contents.json
> Add TSWeChat by @hilen

- contents.json
https://github.com/boostcode/ResearchKit-ColorBlind
> Add Colorblind app by @matteocrippa

- contents.json
Spelled balloon correctly in this edit
> Learning to spell "balloon", one letter at a time

- contents.json
0. [X] Project URL:
1. [X] Update contents.json instead of README 
2. [X] One project per pull request
3. [X] Project added at the end of the list (a script sorts projects automatically)
Since I have contributor access I would normally just commit apps directly. Due to the obvious conflict of interest here however, I'll leave this decision to someone else.
> Add Fibonacc iClock by @scribblemaniac

- contents.json
Just a very small change to add an iTunes link that was missing in a project.
> iTunes link for Brave-ios

- contents.json
0. [x] Project URL: https://github.com/LunarFlash/Chaty
> Add Chaty by @LunarFlash

- contents.json
0. [x] Project URL: https://github.com/omichde/Telemat-tvOS
> add Telemat-tvOS by @omichde

- contents.json
> Added Meme Maker by @Meme-Maker

- .github/osia_get_links.rb
- circle.yml
> Script Update

- .github/osia_get_links.rb
- circle.yml
> Check homepages

- contents.json
Added awesome swift app source
> added awesome swift iOS app

- contents.json
0. [x] Project URL: https://github.com/herrkaefer/CaseAssistant
> Add CaseAssistant

- contents.json
0. [X] Project URL: https://github.com/ryanipete/AmericanChronicle
1. [X] Update contents.json instead of README 
2. [X] One project per pull request
3. [X] Project added at the end of the list (a script sorts projects automatically)
> Add American Chronicle

- contents.json
0. [x] Project URL: https://github.com/JakeLin/SaveTheDot
> Add SaveTheDot by @JakeLin

- contents.json
Updated number of stars for OctoPodium
> Updated Octopodium number of stars

- contents.json
> Add RxMarbles app @RxSwiftCommunity

- contents.json
> Add sip-calculator-swift by @tirupati17

- contents.json
> Add Tagger by @vanyaland

- contents.json
> Add loan-emi-calculator-clean-swift by @tirupati17

- contents.json
0. [x] Project URL: https://github.com/zydeco/minivmac4ios
> Add Mini vMac by @zydeco

- contents.json
0. [x] Project URL: https://github.com/kenmickles/unh_tvos
> Add Uncle Nagy's House tvOS App

- contents.json
> Add Traccar Client and Manager apps

- README.md
- contents.json
0. [x] Project URL: https://github.com/danqing/2048
> Add 2048 by @danqing

- contents.json
Swab – The Content Blocker of Creative, Web and Design Culture Ads
An open-source iOS Content Blocker written in Swift
http://swabthe.com/
> Swab – The Content Blocker of Creative, Web and Design Culture Ads

- contents.json
Adds SHMUP - http://fabiensanglard.net/shmup/
A multiplatform engine primarily written in ANSI C with wrappers for platform specific code, including, of course, iOS.
> Add SHMUP by @fabiensanglard

- contents.json
Adds the `Count It` and the `Send to Me` apps.
> Add Count It and Send to Me apps

- contents.json
> Add Tob by @JRock007

- contents.json
0. [x] Project URL: https://github.com/elpassion/DropColour-iOS
> Add DropColour by @elpassion

- README.md
- contents.json
> Add scholars-of-wwdc by @michieriffic

- contents.json
0. [x] Project URL: https://github.com/jbkuczma/NBAreact
> Add NBAreact by @jbkuczma

- contents.json
> Added Dono

- README.md
- contents.json
> Add UpcomingMovies by @vanyaland

- contents.json
> Added new open source iOS game Alienblast 

- contents.json
> Add Hackfoldr by @superbil

- contents.json
> Add Vector.IM iOS client

- contents.json
0. [x] Project URL: https://github.com/100mango/Celluloid
> Add Celluloid by @100mango

- contents.json
Thanks for taking the time to make contributing this straightforward :)
0. [x] Project URL: https://github.com/jlnr/MovieDict
> Add MovieDict by @jlnr

- contents.json
> Add Californication by @vanyaland

- contents.json
> Add Keinex

- contents.json
> Add tip-calculator by @tirupati17

- contents.json
> Add QR Blank

- circle.yml
- contents.json
Close #393
Note: will merge after Aug 17
> Archive XPilot

- contents.json
1. [ ] Project URL: http://github.com/yavuz/Tenere
> add tenere news reader by @yavuz

- contents.json
> Add OpenStreetView

- contents.json
> Added Swift Snake

- contents.json
> Google Feud for iOS

- contents.json
1. [x] Project URL: https://github.com/evgeniyd/Giraffe
> Add Giraffe by @evgeniyd

- .github/osia_convert.rb
- contents.json
Update layout & cleanup contents
Close #421
> Display Tags

- contents.json
> Add MVVM-Example by @vanyaland

- contents.json
> added my coffee ratio app

- contents.json
> My app is in Swift, not objc, so changed tags

- contents.json
Added tag "swift" for ForceSketch app, because it written in swift.
> Added tags for ForceSketch app.

- contents.json
> Add currency-converter-swift-viper by @tirupati17

- contents.json
I updated the screenshot of my project
> Update screenshot of tpg offline

- contents.json
Credit goes to @leereilly's list https://github.com/leereilly/games
#261
> Add games from leereilly/games

- contents.json
> Add News by @vanyaland

- contents.json
> Add Mergel by @Snazzware

- contents.json
> Added CodeSprint App

- contents.json
> Add HOMEPOK by @iAlexander

- contents.json
> add monotone delay by @jkandzi

- contents.json
> Add Quick Chat

- contents.json
Fixed broken screenshots links (changed to GitHub hosted .jpg file)
> Updated HOMEPOK screenshots by @iAlexander

- contents.json
> Add Popular-Movies by @vanyaland

- contents.json
> Add eCortex 

- contents.json
> Add DailyFeed by @paulsumit1993

- contents.json
1. [X] Project URL: https://github.com/nicolapps/4clock
> Add 4clock by @nicolapps

- contents.json
1. [x] Project URL: https://github.com/Nicholas714/Spin-Zone
> Spin Zone by @Nicholas714

- contents.json
Add ios by @wwdc-family @3lvis 
cc @krausefx
> Add WWDC Family

- contents.json
Hi! I will add screenshots for next project (https://github.com/facebook/react-native/tree/master/Examples):
- 2048
- UIExplorer
Also I tried get screenshots for Movies, but app works wrong :-(
> Add screenshots for reactnative/examples.

- contents.json
Added screenshots for the next projects:
- HealthKit~Swift
- Startups - Mapped In Israel 
- RKGist
- bar
- TextEthan
- prankPro
- MiamiSunglasses
> Add screenshots for some apps.

- contents.json
1. [x] Project URL: https://github.com/richardxyx/BoardBank
> Add BoardBank

- contents.json
1. [x] Project URL: https://github.com/G2Jose/ReactNative-HackerNews
> Add React Native Hacker News by @g2jose

- contents.json
1. [x] Project URL: https://github.com/Flinesoft/Prayer
---
*edited*
> Add Prayer by @Dschee

- contents.json
add LivelyGIFs to json file
1. [x] Project URL: https://github.com/KrisYu/LivelyGIFs
---
*edited*
> Add LivelyGIFs

- contents.json
> added CrimeMapper app

- contents.json
1. [x] Project URL: https://github.com/efremidze/Alarm 
---
*edited*
> Added 420! Alarm

- contents.json
1. [x] Project URL: https://github.com/devxoul/Drrrible
> Add Drrrible by @devxoul

- contents.json
1. [X] Project URL: https://github.com/zntfdr/Compass/
> Add Compass by @zntfdr

- contents.json
> Add 4Pets by @feliborgez

- contents.json
1. [x] Project URL: https://github.com/jnordberg/triggy
5. [ ] ~~Use this commit title format if applicable: Add app-name by @github-username~~ ups
> Add Triggy

- contents.json
This iOS app (iPhone) shows how to use the Zeit Online Content API with Swift 3.
1. [x] Project URL: https://github.com/niftycode/ZeitSuche_iOS
---
*edited*
> add ZeitSuche_iOS by @niftycode

- .github/deploy.sh
- .github/osia_convert.rb
Generate **APPSTORE.md** with only apps that are available on the App Store
Close #490
> Generate App Store only list

- contents.json
1. [x] Project URL: https://github.com/atuooo/notGIF
> Add notGIF by @atuooo

- contents.json
1. [x] Project URL: https://github.com/viniciusvieir/EconoApp
---
*edited*
> Add EconoApp

- contents.json
1. [x] Project URL: https://github.com/argent-os/argent-ios
--- 
*edited*
> Add Argent by @sinanku

- contents.json
> Updating Argent projects tags

- contents.json
1. [x] Project URL: https://github.com/AndrewBennet/readinglist
---
*edited*
> Add Reading List by @AndrewBennet

- contents.json
1. [ ] Project URL: https://github.com/PiXeL16/SnakeClassic
---
*edited*
> Add Snake Classic by @PiXeL16

- contents.json
1. [x] Project URL: https://github.com/artemnovichkov/iOS-11-by-Examples
> iOS 11 by Examples by @artemnovichkov

- contents.json
1. [x] Project URL: https://github.com/alexruperez/MADBike
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dkhamsing/open-source-ios-apps/508)
> Add MADBike by @alexruperez

- contents.json
Add Radium Web Browser
1. [X] Project URL: https://github.com/SlayterDev/RadiumBrowser
> Add Radium Web Browser by @SlayterDev

- contents.json
> Add Stopwatch screenshots.

- contents.json
Added:
- Pokedex
- SimpleWeather
> Add some screenshots

- contents.json
https://github.com/nathantannar4/Parse-Dashboard-for-iOS
> [Addition] Parse Dashboard for iOS

- contents.json
> Add Superday by @vpeschenkov

- contents.json
> Add Crystal Clipboard by @jzzocc

- contents.json
> Add AlohaGIF by @michaello

- contents.json
1. [x] Project URL: https://github.com/crspybits/SharedImages
--- 
*edited*
> Add SharedImages by @crspybits

- contents.json
Thanks for this awesome listing repo. 👍🏼 
Hopefully, I added correctly. Thank you for your consideration. 
1. [x] Project URL: https://github.com/AudioKit/ROMPlayer
> Update Analog Synth X, Add ROM Player by @audiokit

- contents.json
1. [x] Project URL: https://github.com/vkaltyrin/exchanger
> Add Exchanger by @vkaltyrin

- contents.json
1. [x] Project URL: https://github.com/RishabhTayal/ReviewMonitor
> Add ReviewMonitor by @RishabhTayal

- contents.json
1. [x] Project URL: https://github.com/marty-suzuki/iOSDesignPatternSamples
> Add iOSDesignPatternSamples by @marty-suzuki

- contents.json
1. [x] Project URL: https://pisth.github.io
> Add Pisth by @ColdGrub1384

- contents.json
> Added Glucosio entry.

- contents.json
Hello, I removed some tags from my project, tpg-offline, because these tags are no longer relevent. 
1. [X] Project URL: tpg-offline
> Removed some tags from tpg-offline app

- contents.json
> Add RedditWatch by @WillBishop

- contents.json
1. [x ] Project URL:
2. [x ] Update contents.json instead of README 
3. [x ] One project per pull request
4. [x ] Avoid iOS or open-source in description as it is assumed
5. [x ] Use this commit title format if applicable: Add app-name by @github-username
6. [x ] Use approved format for your entry
> Adds Stocks-iOS App

- contents.json
> Add vpeschenkov to credits

- .github/osia_convert.rb
> [script] remove objc default

- contents.json
1. [x] Project URL: https://github.com/Bruno-Furtado/bitprice-ios
> BitPrice App

- contents.json
> Adding Go Flashcards

- contents.json
1. [x] Project URL: https://github.com/xYello/ThePost
> Add The Wave by @SirArkimedes

- contents.json
> Added iTunes link and homepage to Go Flashcards

- contents.json
1. [x] Project URL: https://cozy.io/en/
> Add CozyDrive app by @cozy

- contents.json
Hi! I updated screenshots and tags for Pisth app.
The app is not coded in Objective-C :).
1. [x] Project URL: https://pisth.github.io
> Update Pisth screenshots and tags

- contents.json
Remove rxswift and swift3 tags (no longer accurate), add core-data tag. Update screenshot.
> Update Reading List

- contents.json
1. [x] Project URL: https://github.com/OpenStack-mobile/summit-app-ios
> Added OpenStack Summit by @colemancda

- contents.json
1. [x] Project URL: https://silverfox.be/articles/2018-03-11-textor.html
> Add Textor by @fassko

- contents.json
> Add NearbyWeather by @erikmartens

- contents.json
I found that the image links that I provided don't work unless I add the file extension. I also took the chance to slightly update the description of my project. Sorry for any inconvenience.
> Update NearbyWeather by @erikmartens

- contents.json
My personal project is added. :)
> Game Oh My Plane is added

- contents.json
> added evolution app

- contents.json
Small improvements in information from Evolution. 
#578
> Updated informations from Evolution

- contents.json
> Add RaceRunner and Conjugar by @vermont42

- contents.json
> Add Blahker by @ethanhuang13

- contents.json
1. [x] Project URL: https://github.com/jdisho/Papr
> Add Papr by @jdisho

- contents.json
Signed-off-by: Günther Eberl <guenther@eberl.se>
1. [x] Project URL: https://github.com/geberl/swift-localstorage
> Add Local Storage by @geberl

- contents.json
1. [x] Project URL: https://github.com/rldaulton/queued-music
> Add Queue'd Music by @rldaulton

- .github/osia_convert.rb
- .github/schema.json
- contents.json
> Support Sponsorship

- contents.json
1. [x] Project URL: https://github.com/certificate-helper/TLS-Inspector
> Add TLS Inspector by @murin-matus

- contents.json
Per author's site: "It has come to our attention that this service is being
used in violation of the Yahoo Terms of Service.
As such, the service is being discontinued."
Therefore suggest removing this one from the list (via "archive", per your instructions).
> Archive "Stocks-iOS" app as it is discontinued

- contents.json
1. [x] Project URL: https://github.com/BoostIO/boostnote-mobile
> added boostnote

- contents.json
> Add Transcription helper (new) by @novinfard

- contents.json
1. [x] Project URL: https://github.com/cuappdev/podcast-ios
> Add Recast by @cuappdev

- contents.json
> Replace the camo.* urls (#588)

- contents.json
> Add FityIt by @txaiwieser

- contents.json
1. [x] Project URL: https://github.com/thiagoricieri/Mojilist
> Add Mojilist by @thiagoricieri

- contents.json
1. [x] Project URL: https://github.com/popshootjapan/WeiWallet-iOS
> Add Wei Wallet by @popshootjapan

- contents.json
1. [X] Project URL: https://github.com/sgl0v/WWDCast
> Add WWDCast by @sgl0v

- contents.json
I'm going to remove Shadertweak because the author removed it.
> Archive Shadertweak

- contents.json
It will be fine after merging this #622
> Fix the links

- contents.json
1. [x] Project URL: https://github.com/nightscout/nightguard
> Add Nightguard by @nightscout

- contents.json
1. [x] Project URL: https://github.com/RMizin/FalconMessenger
> Add FalconMessenger by @RMizin

- contents.json
1. [x] Project URL: https://github.com/TortugaPower/BookPlayer
> Add BookPlayer by @GianniCarlo

- contents.json
> Add RichTexture by @stevemoser

- contents.json
> Remove aa-keyboard iTunes link and archive apps

- contents.json
> Add Ladybug by @ethanhuang13

- contents.json
1. [x] Project URL: https://github.com/matiasvillaverde/mobile-ios-vipergame
> Add Memory Game by @matiasvillaverde

- contents.json
> Add Flappy Fly-Bird by @jVirus

- contents.json
1. [x] Project URL: https://github.com/AudioKit/AudioKitSynthOne
> Add AudioKitSynthOne by @AudioKit

- contents.json
> Fix links #643

- contents.json
1. [x] Project URL: https://github.com/twostraws/Unwrap
Close #646
> Add Unwrap by @twostraws

- contents.json
> Add Knil by @ethanhuang13

- contents.json
1. [x] Project URL: https://github.com/willhains/Kotoba
#261
> Add Kotoba by @willhains

- contents.json
> Add Savanna by @louisdh

- contents.json
1. [x] Project URL: https://github.com/smalam119/live-news-viper
#261
> Add live-news-viper by @smalam119

- contents.json
1. [x] Project URL: https://github.com/ltebean/Live
#261
> Add Live by @ltebean

- contents.json
> Update the Linphone app

- contents.json
1. [x] Project URL: https://github.com/imjog/example-ios-apps
#261
> Add example-ios-apps by @imjog

- contents.json
1. [x] Project URL: https://github.com/TheSwiftAlps/GameJam
#261
> Add GameJam by @TheSwiftAlps

- contents.json
> Add SwiftHub by @khoren93

- contents.json
1. [x] Project URL: https://github.com/ay8s/ConfFriends
#261
> Add ConfFriends by @vpeschenkov

- contents.json
> Add MedKeeper by @jonrobinsdev

- contents.json
1. [x] Project URL: https://github.com/noppefoxwolf/DesireKeyboard
#261
> Add DesireKeyboard by @noppefoxwolf

- contents.json
1. [x] Project URL: https://github.com/KeyCoApp/KeyCo
#261
> Add KeyCo by @lojals

- contents.json
1. [x] Project URL: https://github.com/eonist/summon
> Add Summon by @eonist

- contents.json
1. [x] Project URL: https://github.com/archagon/good-spirits
> Added "Good Spirits".

- contents.json
1. [x] Project URL: https://github.com/riley-usagi/SwiftAdvance
> Add Ragnarok by @riley-usagi

- .github/osia_convert.rb
> Fix extra empty lines in Developer, Browser sections

- contents.json
1. [x] Project URL: https://github.com/shu223/iOS-Depth-Sampler
> Add iOS-Depth-Sampler by @shu223

- contents.json
> Remove example-ios-apps from the list

- contents.json
1. [x] Project URL: https://github.com/Stmol/vkphotos
> Add VK Photos by @Stmol

- contents.json
1. [x] Project URL:https://itunes.apple.com/app/id1234567890
6. [x] Use this commit title format if applicable: Add app-name by @github_heikki
> add WeAre-photo album of AR

- contents.json
1. [x] Project URL: https://github.com/marty-suzuki/ArtShredder
> Add ArtShredder by @marty-suzuki

- contents.json
> Add Danbooru Lite by @satishbabariya

- contents.json
> Added Model2App Test App by @karolkulesza

- contents.json
Adds Joplin to the list. [https://github.com/laurent22/joplin](url)
> Add Joplin by @laurent22

- contents.json
> Archive Pickery

- contents.json
> Add Gleam App by @akarataev (#690)

- contents.json
> Add Playerly by @justjs

- contents.json
> added Apple Watch Faces

- contents.json
1. [x] Project URL: https://github.com/Augustyniak/FileExplorer
> Add FileExplorer by @Augustyniak

- contents.json
> Add Betcalsa by @emredurukn

- contents.json
> Update the "Pass" app

- contents.json
> Add TypeStyle by @ebelinski

- contents.json
> add fitPlant by @KrisKodira

- contents.json
> Add GeoLicious by @da3x

- contents.json
> Add Pocket-Code by @painhapp

- contents.json
1. [x] Project URL: https://github.com/madyanov/showio-app
> Add Showio by @madyanov

- contents.json
> Add iSH by @PseudonymPatel

- contents.json
1. [x] Project URL: https://github.com/google/science-journal-ios
> Add google/science-journal-ios 

- contents.json
Small update to description of app.
> Update Science Journal description

- contents.json
1. [ ] Project URL: https://github.com/essentiaone/Essentia-iOS
> Add Essentia

- contents.json
1. [x] Project URL: https://github.com/kuglee/TermiWatch
> Add TermiWatch by @kuglee

- contents.json
The app [pass](https://github.com/davidjb/pass-ios) has been deprecated.
> Archive "pass"

- .github/osia_convert.rb
> Move screenshots below the license

- contents.json
[404](https://httpstatuses.com/404) | https://raw.githubusercontent.com/google/science-journal-ios/master/assets/image1.png 
[404](https://httpstatuses.com/404) | https://raw.githubusercontent.com/google/science-journal-ios/master/assets/image2.png
> Update "Science Journal"

- .github/osia_convert.rb
- Made the title clickable
- Removed the source link from the details
- Added badges to `ARCHIVE.md` (Not sure, let me know what do you think?)
---
[ARCHIVE.md](https://github.com/vpeschenkov/open-source-ios-apps/blob/master/ARCHIVE.md) 
[README.md](https://github.com/vpeschenkov/open-source-ios-apps/blob/master/README.md)
[APPSTORE.md](https://github.com/vpeschenkov/open-source-ios-apps/blob/master/APPSTORE.md)
> Make the title clickable

- contents.json
1. [x] Project URL: https://github.com/Karambirov/GitHubSearch
> Add GitHubSearch by @Karambirov

- contents.json
1. [x] Project URL: https://github.com/k-lpmg/GiTiny
> Add GiTiny by @k-lpmg

- .github/deploy.sh
- .github/osia_convert.rb
> Add LATEST

- contents.json
1. [ ] Project URL: done
2. [ ] Update contents.json instead of README:  yes
3. [ ] One project per pull request: yes
4. [ ] Screenshot included: yes
5. [ ] Avoid iOS or open-source in description as it is assumed: maybe
6. [ ] Use this commit title format if applicable: Add app-name by @github-username: ok
7. [ ] Use approved format for your entry: ok
> Adding Tinodios: https://github.com/tinode/ios

- contents.json
1. [X] Project URL: https://github.com/home-assistant/home-assistant-iOS
> Add Home Assistant Companion

- contents.json
> Add "Home" category

- contents.json
> Add PDF to Keynote.

- contents.json
> Add TicTacToe Ultimatum by @mkhrapov

- .github/osia_convert.rb
[LATEST.MD](https://github.com/vpeschenkov/open-source-ios-apps/blob/master/LATEST.md)
[ARCHIVE.MD](https://github.com/vpeschenkov/open-source-ios-apps/blob/master/ARCHIVE.md)
Close #754
> [script] Remove badges

- contents.json
1. [x] Project URL: https://github.com/WireGuard/wireguard-apple (mirror)
> Add WireGuard by @GETandSELECT

- contents.json
1. [x] Project URL: https://github.com/keepassium/KeePassium
> Add KeePassium by @keepassium

- contents.json
1. [-] Project URL:
3. [-] One project per pull request
4. [-] Screenshot included 
5. [-] Avoid iOS or open-source in description as it is assumed
6. [-] Use this commit title format if applicable: Add app-name by @github-username
7. [-] Use approved format for your entry
> Change Mastodon description URL to more better

- contents.json
Added a link to Decentralized wallet for Bitcoin, Ethereum, EOS, Binance Chain, Bitcoin Cash and DASH blockchains
> Add Unstoppable wallet: an open-source blockchain wallet.

- contents.json
1. [x] Project URL: https://github.com/automat-berlin/afone/
> Add //afone by @rbugajewski

- contents.json
1. [x] Project URL: https://www.ghostery.com/mobile/
> adding Ghostery Browser for iOS

- contents.json
[489](https://github.com/dkhamsing/open-source-ios-apps/pull/772) >> 400
> Fix a few links

- contents.json
> Fix another part of broken links

- contents.json
1. [x] Project URL: https://github.com/Neko3000/Iris.iOS
> Add Iris.iOS by @Neko3000

- contents.json
1. [x] Project URL:https://github.com/Neko3000/Iris.iOS
> Modify screenshot links for Iris.iOS

- contents.json
1. [√] Project URL: https://github.com/ccrama/Slide-iOS
2. [√] Update contents.json instead of README 
3. [√] One project per pull request
4. [√] Screenshot included 
5. [√] Avoid iOS or open-source in description as it is assumed
6. [√] Use this commit title format if applicable: Add app-name by @github-username
7.  [√] Use approved format for your entry
> Add Slide for Reddit by @jinthislife

- contents.json
1. [x] Project URL: https://github.com/nsoojin/BookStore-iOS
> Add BookStore-iOS by @nsoojin

- contents.json
1. [x] Project URL: https://github.com/strongbox-password-safe/Strongbox
Close #783
> Add Strongbox by @strongbox-password-safe

- contents.json
1. [x] Project URL:  https://github.com/arthurhammer/FrameGrabber
> Add Frame Grabber by @arthurhammer

- contents.json
> Added Sansumoku by @mkhrapov

- contents.json
1. [ ] Project URL:https://github.com/passepartoutvpn/passepartout-ios
> Add Passepartout by @keeshux

- contents.json
> Add apps by @tirupati17

- contents.json
1. [x] Project URL: https://github.com/lucanaef/PGPro
> Add PGPro by @lucanaef

- contents.json
> Update WordPress language, screenshot and number of stars

- contents.json
> Add WooCommerce

- contents.json
1. [x] Project URL: https://github.com/AlphaWallet/alpha-wallet-ios
> Add AlphaWallet by @kristiinara

- contents.json
1. [x] Project URL: https://github.com/exantech/exa-wallet-ios
> Add Exa Wallet - Monero by @kristiinara

- contents.json
1. [x] Project URL: https://github.com/ulangi/ulangi
> Add Ulangi by @minhloi

- contents.json
> Adding Ultimate Peg Solitaire

- contents.json
1. [x] Project URL: https://github.com/triangledraw/TriangleDraw-iOS
> Add TriangleDraw

- contents.json
The app is also renamed Tinodios -> Tinode for consistency with other platforms.
1. [+] Project URL:
2. [+] Update contents.json instead of README 
3. [+] One project per pull request
4. [+] Screenshot included 
5. [+] Avoid iOS or open-source in description as it is assumed
6. [-] Use this commit title format if applicable: Add app-name by @github-username
7. [+] Use approved format for your entry
> Update tinodios: link to appstore and another screenshot

- contents.json
Update screenshots for: https://github.com/arthurhammer/FrameGrabber
> Update Frame Grabber by @arthurhammer

- contents.json
1. [x] Project URL: https://github.com/MhdHejazi/CoronaTracker
> Add Corona Tracker by @MhdHejazi

- contents.json
1. [x] Project URL: https://github.com/MartinStamenkovski/LibraryGenesis
> Add Library Genesis

- contents.json
1. [x] Project URL: https://github.com/illu/moonwalk
> Add moonwalk by @illu

- .github/workflows/ruby.yml
- contents.json
Fun stuff https://github.com/dkhamsing/open-source-ios-apps/actions
> Add GitHub Action

- contents.json
> mChat Project

- contents.json
> Add Fingerspelling by @sloria

- contents.json
> Add Podverse 

- .github/workflows/ruby.yml
- contents.json
> Add Outline

- contents.json
1. [x] Project URL: https://github.com/GroupeMINASTE/Delta-iOS
> Add Delta: Math helper by @GroupeMINASTE

- contents.json
> add zeplin ios client app

- contents.json
> Add SimpleLogin

- contents.json
> Add YouTag music player iOS app

- contents.json
> Add MoneyPlus by @SeekingMini

- contents.json
@dkhamsing Thanks for this awesome list! Just fixing a typo I happened to notice for one of the projects.
> Fix typo in contents.json (20202 -> 2020)

- contents.json
1. [x] Project URL:https://github.com/bouk/HTTPS4All
> Add HTTPS4ALL by @bouk

- contents.json
> Add OpenCovidTrace by @shiaulis

- contents.json
Add openfoodfacts by @openfoodfacts
> Add openfoodfacts by @openfoodfacts

- contents.json
> Fix tls-inspector link

- contents.json
1. [x] Project URL: https://github.com/marlon360/grade-calc
> Add GradeCalc by @marlon360

- contents.json
> Add ProtonMail

- contents.json
> Added SpotifyRadar

- contents.json
> Added DivRise

- contents.json
Updating Say Their Names with fresh metadata. The app has been published on the App Store 🥳  
Thanks @dkhamsing for adding it in the first place 💜 
3. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use approved format for your entry
> Update Say Their Names

- contents.json
1.  [x] Project URL: https://pgpro.app (https://github.com/lucanaef/pgpro)
> Update PGPro by @lucanaef

- contents.json
Add ios-sketch-elements
1. [x] Project URL: https://github.com/molcik/ios-sketch-elements 
> Add ios-sketch-elements by @molcik

- contents.json
> Add 'archive' tag to American Chronicle project

- contents.json
1. [x] Project URL: https://github.com/GroupeMINASTE/MorpionTPE-iOS
> Add Tic TAI Toe by @NathanFallet

- contents.json
> Added kontax cam and ghibliii

- contents.json
1. [x] Project URL: https://github.com/GroupeMINASTE/BaseConverter-iOS
> Add BaseConverter by @NathanFallet

- contents.json
> [Addition] AccountBook App

- contents.json
Adding Haptic Haven(published on App Store) to the list! if you haven any questions, my email is davidjacobsen17@gmail.com
> add Haptic Haven

- contents.json
> Added: Pomosh The Productivity timer

- contents.json
Replacement for #880, this time editing the json.
> Update the https in the json this time.

- gatsby/.nvmrc
- gatsby/gatsby-config.js
- gatsby/gatsby-node.js
- gatsby/netlify.toml
- gatsby/package.json
Eventually got the netlify build fixed. Hopefully you merge this and it should Just Work™. Famous last words again!
Relates to #887
> Fixing netlify build

- contents.json
> [script] Update project website

- contents.json
1. -[x] Project URL: https://github.com/TheCodeMonks/NYTimes-iOS
2. -[x] Update contents.json instead of README 
3. -[x] One project per pull request
4. -[x] Screenshot included 
5. -[x] Avoid iOS or open-source in the description as it is assumed
7. -[x] Use the approved format for your entry
6. -[ ] Use this commit title format if applicable: Add app-name by @github-username
> Add NYTimes - SwiftUI by @devwaseem

- contents.json
Added quote today watch os app
> Added a new watch os app

- contents.json
An finace type iOS app using pure code to deisign UI
> add MoneyPlusPro

- contents.json
1. [x] Project URL: https://github.com/NiftyTreeStudios/Bean-Juice
> Add Bean Juice by @Iikeli

- contents.json
> Add KHabit

- contents.json
My new project: https://github.com/jtbandes/SpacePOD
> Add Space!

- README.md
- contents.json
> Feat: Add chatwoot

- contents.json
> Add itunes link for BitPrice

- contents.json
Although it's an old project which ports C code to Objective-C, it might be usable for some
> +Simon Tatham's Portable Puzzle Collection

- contents.json
Added more tags and MIT license.
> Updated Spontaneous - Random quotes

- README.md
- contents.json
> Add CalendarKit by richardtop

- contents.json
1. [x] Project URL: https://github.com/securityfirst/Umbrella_ios
> Added Umbrella by @rorymbyrne

- contents.json
> Add Clendar by @vinhnx

- contents.json
> Add GitTime by @87kangsw

- contents.json
1. [x] Project URL: https://github.com/kyledold/WordOfTheDay
> Add WordOfTheDay by @kyledold

- contents.json
1. [x] Project URL: https://github.com/venkatasg/DeTeXt
> Add DeTeXt by @venkatasg

- .github/osia_convert.rb
- contents.json
The update tweaks the README layout.
The following were removed:
- Date added
- Language 
Before (left) and after (right)
Address #933
> [script] Update layout

- contents.json
For starter Objective-C developers
> Add FakeGithub by @IcedOtaku

- contents.json
> add ZLGithubClient by exsitorlive

- contents.json
1. [x] Project URL: https://github.com/metabolist/metatext
> Add Metatext by @metabolist

- contents.json
> Update contents.json for Shlist app (shopping list)

- contents.json
See https://github.com/RMizin/FalconMessenger/blob/main/LICENSE
> Fix Falcon Messenger license

- contents.json
> Add NetworkArch by @ivirtex

- contents.json
1. [x] Project URL: https://github.com/CovidTrackerFr/vitemadose-ios
> Add Vite Ma Dose de Vaccin ! by @CovidTrackerFr

- contents.json
> Add Mullvad VPN by @mullvad

- contents.json
> Add Collected

- contents.json
> Add CalendarApp by richardtop

- contents.json
In this PR I'm not adding a new repo, but updating an existing one, which was renamed.
> Updated a repo that was renamed

- contents.json
> Add Chanify by @wizjin

- contents.json
> Add microblog-ios

- contents.json
> Add BarcodeScanner

- contents.json
> Add Fearless Wallet

- contents.json
1. [x] Project URL: [https://github.com/tatsuz0u/EhPanda](url)
> Add EhPanda by @tatsuz0u

- contents.json
1. [x] Project URL: https://github.com/honjow/FEhViewer
> Add FEhViewer by @honjow

- contents.json
> Add EU VAT Number - VIES Freelance by @FranicevicNikola

- contents.json
> Add Stop-COVID-19-Croatia/stopcovid19-ios

- contents.json
> Add Platypus Crypto

- contents.json
> Add Koronavilkku

- contents.json
> Add ar-multipendulum by @philipturner

- contents.json
> Update Provenance screenshots

- contents.json
1. [x] Project URL: https://github.com/AlexCatch/Oak
> Add OakOTP by @alexcatch

- contents.json
1. [x] Project URL: https://github.com/AnthonyH93/GoCycling
> Add Go Cycling by @AnthonyH93

- contents.json
> Add Amplosion

- contents.json
> Add Rainbow by @rainbow-me

- contents.json
> Add SpotifyClone by @gabrieldenoni

- contents.json
> Add Droidcon

- contents.json
Proposed Elseweather - app that displays current weather at a random location.
> Elseweather

- contents.json
> Add Scribe - Language Keyboards by @scribe-org

- contents.json
Adding the app store link and a link to the organization's page as the homepage.
This is really great :)
1. [x] Project URL
> Edit Scribe - Language Keyboards by @scribe-org

- contents.json
> Update Spare Parts screenshot

- contents.json
> Update Wolfenstein 3D screenshots

- contents.json
> Update PhishOD screenshots

- contents.json
> Update FreeOTP Authenticator

- contents.json
> Update ehpanda screenshots

- contents.json
> Add Stay by @shenruisi

- contents.json
1. [x] Project URL: https://github.com/sindresorhus/Actions
The built-in [Shortcuts](https://9to5mac.com/2021/06/20/macos-monterey-shortcuts-app/) app is very useful for automating things. However, there are many essential actions that it lacks. This app provides the missing pieces, making it easier to create shortcuts. This app solves a lot of problems for people using Shortcuts, which is a lot of users. You can think of this app as a toolbelt for Shortcuts.
> Add Actions by @sindresorhus

- contents.json
> Remove project website

- contents.json
https://www.atrinh.com/covid/index.html
https://github.com/atrinh0/covid19
> Add UK COVID-19 Statistics by @atrinh0

- contents.json
> Add MakeItSo by @peterfriese

- contents.json
> Add My Little Popcat by @ChoiysApple

- README.md
> Update Count It

- contents.json
> Add TwitterSentiment by @draese

- contents.json
> Add vocable-ios by @willowtreeapps

- contents.json
> Add E-Rezept-App-iOS by @gematik

- contents.json
1. [x] Project URL: https://github.com/AnthonyH93/HexaCalc
> Add HexaCalc by @AnthonyH93

- contents.json
1. [ x] Project URL:  https://github.com/Livinglist/Hacki
2. [ x] Update contents.json instead of README 
3. [ x] One project per pull request
4. [ x] Screenshot included 
5. [ x] Avoid iOS or open-source in description as it is assumed
6. [ x] Use this commit title format if applicable: Add app-name by @github-username
7. [ x] Use approved format for your entry
> Add Hacki by @livinglist

- contents.json
> Add Projector by @fthgrsy27

- contents.json
> Add QZ by @cagnulein

- contents.json
> Adds Instagram SwiftUI.

- contents.json
> added PrivacyBlur by @MATHEMA-GmbH

- contents.json
1. [x] Project URL: https://github.com/mastodon/mastodon-ios
7. [x] Use approved format for your entry **(with the `stars`, `tags` and `license` keyworks in addition)**
> Add mastodon's official app by @mastodon

- contents.json
> Add BreadBuddy

- contents.json
> Add Threema

- contents.json
> Add Critical Maps by @mltbnz

- contents.json
> Add Asteroid+ by @ChoiysApple

- contents.json
I'm reorganizing the repo to put GH only images in .github. Realized that I should update the path here :)
> Update Scribe description and image location

- contents.json
> Add Pong by @dduan

- contents.json
> Add Zeitgeist

- contents.json
> Add Domination

- contents.json
Fix https://github.com/dkhamsing/open-source-ios-apps/actions/runs/2804608243
> Update Related Messenger screenshots

- contents.json
1. [x] Project URL :https://migrainelog.zerodogg.org
> Add Migraine Log by @zerodogg

- contents.json
1. [x] Project URL: https://skiff.com/mail
> Add Skiff Mail by @skiff-org

- contents.json
1. [x] Project URL: https://www.jaydenirwin.com/spritepencil/
> Add Sprite Pencil by @256ArtsDeveloper

- contents.json
1. [x] Project URL: https://lemonpepperseasoning.github.io/hasha/
> Add Hasha by @LemonPepperSeasoning

- contents.json
> Add Cuisiner

- contents.json
1. [x] Project URL: https://www.jaydenirwin.com/spritecatalog/
> Add Sprite Catalog by @256ArtsDeveloper

- contents.json
> Add Expenses Tracker

- contents.json
1. [x] Project URL: https://www.jaydenirwin.com/spritefonts/
> Add Sprite Fonts by @256ArtsDeveloper

- contents.json
1. [x] Project URL: https://www.jaydenirwin.com/myassets/
> Add My Assets by @256ArtsDeveloper

- contents.json
1. [x] Project URL: https://www.jaydenirwin.com/sfcode/
> Add Symbol Code by @256ArtsDeveloper

- contents.json
> Added Project Democracy app

- contents.json
1. [x] Project URL: https://www.jaydenirwin.com/spaceui/
> Add SpaceUI by @256ArtsDeveloper

- contents.json
> Added MoodSnap mood diary

- contents.json
> added Gym Routine Tracker Watch App

- contents.json
> Add airdash by @simonbengtsson

- contents.json
Added Loadify iOS App to the open source list. Loadify is an iOS App that will download YouTube videos and save it to the gallery
> Add Loadify

- contents.json
> Add GistHub by @ldakhoa

- contents.json
> Add StormyLaunch by @Sendeky

- contents.json
1. [x] Project URL: https://github.com/mshll/Color-Way
> Add Color Way

- contents.json
1. [x] Project URL: https://github.com/WezSieTato/ScanNow
> Add Scan Now app

- contents.json
> Add Flippy Learn by @misteu

- contents.json
1. [x] Project URL: https://github.com/ritwiktakkar/shorten_my_URL
> Add ShortenMyURL by @ritwiktakkar

- contents.json
1. [x] Project URL: https://github.com/ritwiktakkar/WordDefiner
> Add WordDefiner English Dictionary by @ritwiktakkar

- LATEST.md
- contents.json
> Add Space Empires

- contents.json
> Add Habo by @xpavle00

- contents.json
> Update RedditWatch screenshots

- contents.json
> Update connectivity demo screenshot

- contents.json
> Add EasyCrypto

- LATEST.md
- contents.json
> Add Find Seat 

- contents.json
> Update WatchPics screenshot

- contents.json
> Add Toilet Radar Paris

- contents.json
1. [x] Project URL: https://github.com/Livinglist/ZCombinator
> Add Z Combinator

- contents.json
> Add uhohlingo

- contents.json
> Add Bluesky

- contents.json
> Update Five In A Row

- contents.json
1. [x] Project URL: https://github.com/streetwriters/notesnook
> Add Notesnook by @ammarahm-ed

- contents.json
> Update Dungeon Crawl

- contents.json
> Update Flappy Bird clone

- contents.json
> Update Snake clone

- contents.json
> Add Kurozora

- contents.json
> Update Cocktail menu

- contents.json
> Archive Brain Marks

- contents.json
> Update Google Feud

- contents.json
> Update Hostile Takeover

- contents.json
> Update Coffee Ratio

- contents.json
> Update Vapor Chat

- contents.json
> Update try! Swift NYC

- contents.json
> Add Proton Drive

- contents.json
> Update Face Landmarks Detection

- contents.json
> Added Frozen Bubble Game

- contents.json
> Archive Frame Grabber

- contents.json
> Update Frozen Bubble

- contents.json
> Update Suicide prevention

- contents.json
> Update Proton Drive

- contents.json
> Update Tofu Authenticator

- contents.json
> Update AC Helper

- contents.json
> Update Stopp Corona

- contents.json
> Remove LivescoreApp

- contents.json
> Update Bristol Pound

- contents.json
> Update GitHub contributions widget

- contents.json
> Update Evolution categories

- contents.json
> Update Jitsi Meet

- contents.json
> Update Tell Time

- contents.json
> Update Formant Plotter

- contents.json
> Update 8 Ball Answers

- contents.json
> Update App Switcher

- contents.json
> Update NHS COVID-19

- contents.json
> Update Sunshine Weather

- contents.json
> Update Restaurant Viewing

- contents.json
> Update COVID Alert

- contents.json
> Update Covid Watch

- contents.json
> Add Frosty

- contents.json
> Add Swordfish

- contents.json
> Add MultiBuddy

- contents.json
> Update Parse Developer Day

- contents.json
> Update Endless Browser

- contents.json
> Update Coffee Timer

- contents.json
> Archive Skiff

- contents.json
> Add Logseq

- contents.json
> Add Concertmaster Player

- contents.json
> Update GitHub API Client

- contents.json
> Update To do

- contents.json
> Update Spin Zone

- contents.json
1. [x] Project URL: [https://github.com/mateusz-bak/openreads](https://github.com/mateusz-bak/openreads)
> Add Openreads

- contents.json
> Update Balloon Burst

- contents.json
> Update My First Memory

- contents.json
> Update Abby's Cycle

- contents.json
> Add Funkin

- contents.json
1. [x] Project URL: https://github.com/infinitepower18/Homepage-MobileSafari
> Add Homepage

- contents.json
> Add Exercism

- contents.json
> Update Whatsapp clone

- contents.json
> Update Snapchat clone

- contents.json
> Update Pokemon Go clone

- contents.json
> Update Tinder clone

- contents.json
> Update Twitter clone

- contents.json
> Update FC Barcelona

- contents.json
> Update Local Storage

- contents.json
> Update DVD Collection Tracker

- contents.json
> Add Physics

- contents.json
> Add Particles

- contents.json
A free & open-source music visualizer, written with modern Swift/SwiftUI APIs.
1. [x] Project URL: https://github.com/Keith-43/MuVis
> Add MuVis app by @Treata11

- contents.json
added Betbudd a bet tracking application
> Add BetBudd by @bigjermaine

- contents.json
> Add nate-parrott/tortellini

- contents.json
> Add wvabrinskas/PokePal

- contents.json
Found in https://github.com/dkhamsing/open-source-ios-apps/actions/runs/9860334806/job/27226242156
> Update Sketch Elements

- contents.json
> Archive Raivo

- contents.json
> Add BOT-anist

- contents.json
> Add Destination Video

- contents.json
> Add dl-alexandre/SymbolView

- contents.json
> Archive aaronpearce/SF-Viewer

- contents.json
> Archive shenruisi/Stay

- contents.json
> Add apps by @YusuFKaan48

- contents.json
> Add apps by @denissimon

- contents.json
> Add PetNote by @XunMengWinter

- contents.json
> Add Chronos

- contents.json
> Add Tab navigation sample

- contents.json
> Add Simulating physics joints

- contents.json
> Add RoomPlan

- contents.json
> Add SKTetris by @chsxf

- contents.json
1. [x] Project URL: https://gitlab.com/Pomelo-Emu/Pomelo
> Add Pomelo by @stossy11

- contents.json
Apologies for missing the auto-formatting on the last one. Thanks!
> Add KFinder by @robertwtucker

- contents.json
> Add Element X by @Velin92

- contents.json
> Archive apps

- contents.json
1. [x] Project URL: https://github.com/lcandy2/neodb-app
6. [x] Use this commit title format if applicable: Add app-name by @lcandy2
> Add Piecelet 

- contents.json
> Add PomPadDo

- contents.json
> Archive Actions

- contents.json
> Add onionshare

- contents.json
1. [x] Project URL: https://github.com/csprasad/Mr-Tip
> Add Mr.Tip by @csprasad

- contents.json
> Add QR Share Pro and Recap AI

- contents.json
1. [x] Project URL: https://github.com/lukhnos/roundandsplit
> Archive Round & Split

- contents.json
1. [x] Project URL: https://github.com/thedillonb/CodeBucket
> Archive CodeBucket

- contents.json
1. [x] Project URL: https://github.com/anonrig/zeplin-ios
> Archive Zeplin

- contents.json
1. [x] Project URL: https://github.com/rlwimi/major-input
> Archive Major Input

- contents.json
1. [x] Project URL: https://github.com/mozilla-mobile/focus-ios
> Archive Firefox Focus

- contents.json
1. [x] Project URL: https://github.com/lexrus/VPNOn
> Archive VPNOn

- contents.json
> Add CraftOS-PC

- contents.json
1. [x] Project URL: https://github.com/OneBusAway/onebusaway-iphone
> Archive OneBusAway

- contents.json
1. [x] Project URL: https://github.com/acani/Chats
> Archive Chats

- contents.json
> Cleanup Recap AI

- contents.json
> Cleanup QR Share Pro

- contents.json
1. [x] Project URL: https://github.com/sugarso/MappedInIsrael
> Archive Startups - Mapped In Israel

- contents.json
1. [x] Project URL: https://github.com/duckduckgo/ios
> Archive DuckDuckGo

- contents.json
> Add DuckDuckGo

- contents.json
1. [x] Project URL: https://github.com/RocketChat/Rocket.Chat.iOS
> Archive Rocket.Chat

- contents.json
1. [x] Project URL: https://github.com/danylokos/popcorntime-ios
> Archive PopcornTime

- contents.json
1. [x] Project URL: https://github.com/crashlytics/cannonball-ios
> Archive Cannonball

- contents.json
1. [x] Project URL: https://github.com/basarsubasi/simplefitnessapp
> Add Simple. by @basarsubasi

- contents.json
1. [x] Project URL: https://github.com/stevemoser/richtexture
close #1824
> Archive RichTexture 

- contents.json
1. [x] Project URL: https://github.com/MiniKeePass/MiniKeePass
> Archive MiniKeePass

- contents.json
1. [x] Project URL: https://github.com/appsquickly/Typhoon-Swift-Example
> Archive Pocket Forecast

- contents.json
1. [x] Project URL: https://github.com/ashfurrow/C-41
> Archive C-41

- contents.json
1. [x] Project URL: https://github.com/devxoul/Drrrible
> Archive Drrrible

- contents.json
> Add Clearcam by @roryclear

- contents.json
1. [x] Project URL: https://github.com/zizicici/Off-Day
> Add Off-Day

- contents.json
1. [x] Project URL: https://github.com/TrustWallet/trust-wallet-ios
> Archive Trust(wallet)

- contents.json
1. [x] Project URL: https://github.com/eerimoq/moblin
> Add Moblin

- contents.json
1. [x] Project URL: https://github.com/sigfault-byte/LegitURL
> Add LegitURL

- contents.json
1. [x] Project URL: https://github.com/asuc-octo/berkeley-mobile-ios
> Add Berkeley Mobile

- contents.json
1. [x] Project URL: https://github.com/artsy/eidolon
> Archive Kiosk

- contents.json
1. [x] Project URL: https://github.com/GitHawkApp/GitHawk
> Archive GitHawk

- contents.json
1. [x] Project URL: https://github.com/microdotblog/strata
#1866
> Add Strata

- contents.json
update Pocket Casts appstore link - #1866
> Update Pocket Casts

- contents.json
1. [x] Project URL: https://github.com/Haptic-Apps/Slide-iOS
> Archive Slide for Reddit

- contents.json
1. [x] Project URL: https://github.com/CodeHubApp/CodeHub
> Archive CodeHub

- contents.json
1. [x] Project URL: https://github.com/THLfi/koronavilkku-ios
> Archive Finland - Koronavilkku

- contents.json
1. [x] Project URL: https://github.com/MoralCode/MetricTime
> Archive MetricTime

- contents.json
1. [x] Project URL: https://github.com/NathanFallet/MorpionTPE-iOS
> Archive Tic TAI Toe

- contents.json
Updated homepage URLs
Archived 2 apps:
1. [x] Project URL: https://github.com/256Arts/Sprite-Fonts
1. [x] Project URL: https://github.com/256Arts/Symbol-Code
> Update 256 Arts app URLs

- contents.json
1. [x] Project URL: https://github.com/admin-ch/CovidCertificate-App-iOS
> Archive Covid Certificate

- contents.json
1. [x] Project URL: https://github.com/ivan-magda/UpcomingMovies
> Archive Upcoming Movies

- contents.json
1. [x] Project URL: https://github.com/ivan-magda/Tagger
> Archive Tagger

- contents.json
1. [x] Project URL: https://github.com/bartonhammond/snowflake
> Archive Snowflake

- contents.json
1. [x] Project URL: https://github.com/covid19cz/erouska-ios
> Archive eRouška

- contents.json
1. [x] Project URL: https://github.com/soroushchehresa/iran-coronavirus
> Archive Iran-coronavirus

- contents.json
1. [x] Project URL: https://github.com/minvws/nl-covid19-notification-app-ios
> Archive Netherlands - COVID19

- contents.json
1. [x] Project URL: https://github.com/openfoodfacts/openfoodfacts-ios
> Archive Open food facts

- contents.json
1. [x] Project URL: https://github.com/tpgoffline/tpg-offline-iOS
> Archive tpg-offline

- contents.json
#1936 
1. [x] Project URL: https://github.com/bitwarden/ios
> Add updated Bitwarden

- contents.json
1. [x] Project URL: https://github.com/insidegui/AnimojiStudio
> Archive Animoji Studio

- contents.json
1. [x] Project URL: https://github.com/sahilsatralkar/ContextComposer
2. [ ] Add `archive` tag
> Add ContextComposer by @sahilsatralkar

- contents.json
1. [x] Project URL: https://github.com/metabolist/metatext
> Archive Metatext

- contents.json
1. [x] Project URL: https://github.com/ViniciusDeep/Revill
> Archive Revill

- contents.json
1. [x] Project URL: https://github.com/microdotblog/microblog-ios
> Archive Micro.blog

- contents.json
1. [X] Project URL: https://github.com/Jaennaet/pISSStream
2. [X] Add `archive` tag
> Add pISSStream

- contents.json
1. [x] Project URL: https://github.com/huggingface/swift-coreml-transformers
> Archive Swift-coreml-transformers
